name: CD
run-name: ${{ github.actor }} is running CD
on:
  push:
    branches: [ main ]

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2

      # set node version
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Deploy to GH Pages
        # run the deploy script
        run: |
          npm install
          npm run deploy
